apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app_environment_id: 581c0043-d202-442c-8e09-defb125c48a4
    env_id: 7d8dc4ed-9816-4f08-8b50-e2fd188b057f
    env_name: testcritical
    organization_id: 6c869bc0-38b8-4504-bfed-9c5da7c8f15a
    platformer_app_id: 8e72a7ad-a394-42e3-be56-5c5e3463a0e4
    platformer_app_name: active
    platformer_component: rudder
    platformer_system: "true"
    project_id: 165f9b1a-b501-457f-902b-ac957491213c
    test: kcd
  name: active-default-env-3192360657
  namespace: criticaltest
spec:
  ports:
  - name: port-8081
    port: 8080
    targetPort: 8081
  selector:
    app_environment_id: 581c0043-d202-442c-8e09-defb125c48a4
    env_id: 7d8dc4ed-9816-4f08-8b50-e2fd188b057f
    env_name: testcritical
    organization_id: 6c869bc0-38b8-4504-bfed-9c5da7c8f15a
    platformer_app_id: 8e72a7ad-a394-42e3-be56-5c5e3463a0e4
    platformer_app_name: active
    platformer_component: rudder
    platformer_system: "true"
    project_id: 165f9b1a-b501-457f-902b-ac957491213c
  type: ClusterIP
