apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: null
  labels:
    app_environment_id: 7a572d38-8698-4b7f-a86c-80cfb9b41689
    env_id: ce77a8f9-bf57-4b39-92ea-c6183b90b279
    env_name: t2
    hpa_id: f68b433c-3f8d-484a-ab3a-fa3334a2c67a
    organization_id: 6c869bc0-38b8-4504-bfed-9c5da7c8f15a
    platformer_app_id: 8e72a7ad-a394-42e3-be56-5c5e3463a0e4
    platformer_app_name: active
    platformer_component: rudder
    platformer_system: "true"
    project_id: 165f9b1a-b501-457f-902b-ac957491213c
  name: active-default-env-3192360657
  namespace: rtyrt
spec:
  maxReplicas: 3
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: active-default-env-3192360657
