apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: null
  labels:
    app_environment_id: 5d360e73-6534-4ba5-99ed-849daddad555
    env_id: c392930e-6a09-470d-9de0-59a2372ceb08
    env_name: default-env
    hpa_id: 403df0ff-38f4-4c5c-9148-215d860c3809
    organization_id: 6c869bc0-38b8-4504-bfed-9c5da7c8f15a
    platformer_app_id: 8e72a7ad-a394-42e3-be56-5c5e3463a0e4
    platformer_app_name: active
    platformer_component: rudder
    platformer_system: "true"
    project_id: 165f9b1a-b501-457f-902b-ac957491213c
  name: active-default-env-3192360657
  namespace: default-env1593166500865
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 10
    type: Resource
  - resource:
      name: memory
      targetAverageValue: 68Mi
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: active-default-env-3192360657
