apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  annotations: null
  labels:
    app_environment_id: 6f40ba81-ab9a-44c4-806d-89f9ac1c369e
    env_id: 6a2c7519-2e36-4b54-be62-196b1a7a01d7
    env_name: ns-test
    organization_id: 6c869bc0-38b8-4504-bfed-9c5da7c8f15a
    platformer_app_id: 8e72a7ad-a394-42e3-be56-5c5e3463a0e4
    platformer_app_name: active
    platformer_component: rudder
    platformer_system: "true"
    project_id: 165f9b1a-b501-457f-902b-ac957491213c
    vpa_id: bbe098e6-0f8e-4d94-832b-0c6528bec05f
  name: active
  namespace: test-multiple-ns
spec:
  resourcePolicy: {}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: active
  updatePolicy:
    updateMode: "Off"
